export interface ExerciseEntry {
  name: string;
  muscle: string;
  equipment?: string;
  /** Secondary/stabilizer muscles, when meaningful. */
  secondary?: string;
  /** Movement classification for smarter volume planning. */
  type?: 'Compound' | 'Isolation';
}

export const EXERCISE_LIBRARY: ExerciseEntry[] = [
  // ── Chest ──
  { name: 'Bench Press', muscle: 'Chest', equipment: 'Barbell' },
  { name: 'Incline Bench Press', muscle: 'Chest', equipment: 'Barbell' },
  { name: 'Decline Bench Press', muscle: 'Chest', equipment: 'Barbell' },
  { name: 'Dumbbell Bench Press', muscle: 'Chest', equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Press', muscle: 'Chest', equipment: 'Dumbbell' },
  { name: 'Decline Dumbbell Press', muscle: 'Chest', equipment: 'Dumbbell' },
  { name: 'Dumbbell Fly', muscle: 'Chest', equipment: 'Dumbbell' },
  { name: 'Cable Crossover', muscle: 'Chest', equipment: 'Cable' },
  { name: 'Cable Fly (High)', muscle: 'Chest', equipment: 'Cable' },
  { name: 'Cable Fly (Low)', muscle: 'Chest', equipment: 'Cable' },
  { name: 'Pec Deck Fly', muscle: 'Chest', equipment: 'Machine' },
  { name: 'Machine Chest Press', muscle: 'Chest', equipment: 'Machine' },
  { name: 'Push-Up', muscle: 'Chest', equipment: 'Bodyweight' },
  { name: 'Wide Push-Up', muscle: 'Chest', equipment: 'Bodyweight' },
  { name: 'Decline Push-Up', muscle: 'Chest', equipment: 'Bodyweight' },
  { name: 'Chest Dip', muscle: 'Chest', equipment: 'Bodyweight' },
  { name: 'Dumbbell Pullover', muscle: 'Chest', equipment: 'Dumbbell' },
  { name: 'Svend Press', muscle: 'Chest', equipment: 'Plate' },
  { name: 'Landmine Press', muscle: 'Chest', equipment: 'Barbell' },
  { name: 'Hex Press', muscle: 'Chest', equipment: 'Dumbbell' },
  { name: 'Floor Press', muscle: 'Chest', equipment: 'Barbell' },
  { name: 'Kettlebell Press', muscle: 'Chest', equipment: 'Kettlebell' },
  { name: 'Incline Cable Fly', muscle: 'Chest', equipment: 'Cable', type: 'Isolation', secondary: 'Shoulders' },
  { name: 'Low-to-High Cable Fly', muscle: 'Chest', equipment: 'Cable', type: 'Isolation', secondary: 'Shoulders' },
  { name: 'Neutral-Grip Dumbbell Bench', muscle: 'Chest', equipment: 'Dumbbell', type: 'Compound', secondary: 'Triceps' },
  { name: 'Single-Arm Dumbbell Bench', muscle: 'Chest', equipment: 'Dumbbell', type: 'Compound', secondary: 'Core' },
  { name: 'Machine Fly', muscle: 'Chest', equipment: 'Machine', type: 'Isolation' },
  { name: 'Dumbbell Incline Fly', muscle: 'Chest', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Shoulders' },
  { name: 'Weighted Push-Up', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },
  { name: 'Deficit Push-Up', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },
  { name: 'Chest Press (Resistance Band)', muscle: 'Chest', equipment: 'Band', type: 'Compound', secondary: 'Triceps' },
  { name: 'Flies (Resistance Band)', muscle: 'Chest', equipment: 'Band', type: 'Isolation' },
  { name: 'Smith Machine Bench Press', muscle: 'Chest', equipment: 'Machine', type: 'Compound', secondary: 'Triceps' },
  { name: 'Smith Machine Incline Press', muscle: 'Chest', equipment: 'Machine', type: 'Compound', secondary: 'Triceps' },
  { name: 'Isometric Chest Squeeze', muscle: 'Chest', equipment: 'Plate', type: 'Isolation' },
  { name: 'Dumbbell Squeeze Press', muscle: 'Chest', equipment: 'Dumbbell', type: 'Compound', secondary: 'Triceps' },
  { name: 'Plyometric Push-Up', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },
  { name: 'Feet-Elevated Push-Up', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Cable Press (Standing)', muscle: 'Chest', equipment: 'Cable', type: 'Compound', secondary: 'Triceps' },
  { name: 'Reverse-Grip Bench Press', muscle: 'Chest', equipment: 'Barbell', type: 'Compound', secondary: 'Triceps' },
  { name: 'Guillotine Press', muscle: 'Chest', equipment: 'Barbell', type: 'Compound', secondary: 'Triceps' },
  { name: 'Incline Push-Up', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },
  { name: 'Ring Dip (chest)', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },

  // ── Back ──
  { name: 'Deadlift', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Sumo Deadlift', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Trap Bar Deadlift', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Snatch Grip Deadlift', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Rack Pull', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Barbell Row', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Pendlay Row', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Yates Row', muscle: 'Back', equipment: 'Barbell' },
  { name: 'T-Bar Row', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Seated Cable Row', muscle: 'Back', equipment: 'Cable' },
  { name: 'Single Arm Dumbbell Row', muscle: 'Back', equipment: 'Dumbbell' },
  { name: 'Two Arm Dumbbell Row', muscle: 'Back', equipment: 'Dumbbell' },
  { name: 'Kroc Row', muscle: 'Back', equipment: 'Dumbbell' },
  { name: 'Meadows Row', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Pull-Up', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Wide Pull-Up', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Chin-Up', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Neutral Grip Pull-Up', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Lat Pulldown', muscle: 'Back', equipment: 'Cable' },
  { name: 'Wide Grip Lat Pulldown', muscle: 'Back', equipment: 'Cable' },
  { name: 'Reverse Grip Pulldown', muscle: 'Back', equipment: 'Cable' },
  { name: 'Straight Arm Pulldown', muscle: 'Back', equipment: 'Cable' },
  { name: 'Romanian Deadlift', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Hyperextension', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Good Morning', muscle: 'Back', equipment: 'Barbell' },
  { name: 'Reverse Fly', muscle: 'Back', equipment: 'Dumbbell' },
  { name: 'Cable Pull-Through', muscle: 'Back', equipment: 'Cable' },
  { name: 'Band Pull-Apart', muscle: 'Back', equipment: 'Band' },
  { name: 'Inverted Row', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Muscle-Up', muscle: 'Back', equipment: 'Bodyweight' },
  { name: 'Underhand Barbell Row', muscle: 'Back', equipment: 'Barbell', type: 'Compound', secondary: 'Biceps' },
  { name: 'Chest-Supported Row', muscle: 'Back', equipment: 'Machine', type: 'Compound', secondary: 'Biceps' },
  { name: 'Dumbbell Row (Bench Supported)', muscle: 'Back', equipment: 'Dumbbell', type: 'Compound', secondary: 'Biceps' },
  { name: 'Seated Cable Row (V-Grip)', muscle: 'Back', equipment: 'Cable', type: 'Compound', secondary: 'Biceps' },
  { name: 'Close-Grip Lat Pulldown', muscle: 'Back', equipment: 'Cable', type: 'Compound', secondary: 'Biceps' },
  { name: 'Single-Arm Lat Pulldown', muscle: 'Back', equipment: 'Cable', type: 'Compound', secondary: 'Biceps' },
  { name: 'Machine Rear Delt Row', muscle: 'Back', equipment: 'Machine', type: 'Isolation', secondary: 'Rear Delts' },
  { name: 'Cable Face Row', muscle: 'Back', equipment: 'Cable', type: 'Isolation', secondary: 'Rear Delts' },
  { name: 'Supine Row', muscle: 'Back', equipment: 'Bodyweight', type: 'Compound', secondary: 'Biceps' },
  { name: 'Ring Row', muscle: 'Back', equipment: 'Bodyweight', type: 'Compound', secondary: 'Biceps' },
  { name: 'Pull-Up (Weighted)', muscle: 'Back', equipment: 'Bodyweight', type: 'Compound', secondary: 'Biceps' },
  { name: 'Commando Pull-Up', muscle: 'Back', equipment: 'Bodyweight', type: 'Compound', secondary: 'Biceps' },
  { name: 'Archer Pull-Up', muscle: 'Back', equipment: 'Bodyweight', type: 'Compound', secondary: 'Biceps' },
  { name: 'American Deadlift', muscle: 'Back', equipment: 'Barbell', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Deficit Deadlift', muscle: 'Back', equipment: 'Barbell', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Paused Deadlift', muscle: 'Back', equipment: 'Barbell', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Snatch-Grip RDL', muscle: 'Back', equipment: 'Barbell', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Pull-Through (Band)', muscle: 'Back', equipment: 'Band', type: 'Compound', secondary: 'Glutes' },
  { name: 'Back Extension (Roman Chair)', muscle: 'Back', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Glutes' },
  { name: 'Loaded Carry (Single Arm)', muscle: 'Back', equipment: 'Dumbbell', type: 'Compound', secondary: 'Core' },
  { name: 'EZ Bar Pullover', muscle: 'Back', equipment: 'Barbell', type: 'Compound', secondary: 'Chest' },
  { name: 'Cable Face Pull (high)', muscle: 'Back', equipment: 'Cable', type: 'Isolation', secondary: 'Rear Delts' },
  { name: 'Rowing Machine (power)', muscle: 'Back', equipment: 'Machine', type: 'Compound', secondary: 'Full Body' },

  // ── Shoulders ──
  { name: 'Overhead Press', muscle: 'Shoulders', equipment: 'Barbell' },
  { name: 'Seated Dumbbell Press', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Arnold Press', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Push Press', muscle: 'Shoulders', equipment: 'Barbell' },
  { name: 'Z Press', muscle: 'Shoulders', equipment: 'Barbell' },
  { name: 'Dumbbell Lateral Raise', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Cable Lateral Raise', muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Leaning Lateral Raise', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Front Raise', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Cable Front Raise', muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Plate Front Raise', muscle: 'Shoulders', equipment: 'Plate' },
  { name: 'Face Pull', muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Reverse Fly', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Upright Row', muscle: 'Shoulders', equipment: 'Barbell' },
  { name: 'Cable Upright Row', muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Scaption Raise', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Cuban Press', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Incline Y-Raise', muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Handstand Push-Up', muscle: 'Shoulders', equipment: 'Bodyweight' },
  { name: 'Pike Push-Up', muscle: 'Shoulders', equipment: 'Bodyweight' },
  { name: 'Neutral-Grip Overhead Press', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Compound', secondary: 'Triceps' },
  { name: 'Single-Arm Overhead Press', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Compound', secondary: 'Core' },
  { name: 'Machine Shoulder Press', muscle: 'Shoulders', equipment: 'Machine', type: 'Compound', secondary: 'Triceps' },
  { name: 'Smith Machine OHP', muscle: 'Shoulders', equipment: 'Machine', type: 'Compound', secondary: 'Triceps' },
  { name: 'Trap Bar Overhead Press', muscle: 'Shoulders', equipment: 'Barbell', type: 'Compound', secondary: 'Triceps' },
  { name: 'Dumbbell Rear-Delt Row', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Back' },
  { name: 'Cable Rear Delt Fly', muscle: 'Shoulders', equipment: 'Cable', type: 'Isolation', secondary: 'Back' },
  { name: 'Band Lateral Raise', muscle: 'Shoulders', equipment: 'Band', type: 'Isolation' },
  { name: 'Band Pull-Apart (rear delt)', muscle: 'Shoulders', equipment: 'Band', type: 'Isolation', secondary: 'Back' },
  { name: 'Y-Raise (Prone)', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Back' },
  { name: 'T-Raise', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Traps' },
  { name: 'W-Raise', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Plate Halos', muscle: 'Shoulders', equipment: 'Plate', type: 'Isolation', secondary: 'Core' },
  { name: 'Dumbbell Shrug (rear)', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Traps' },
  { name: 'Seated Lateral Raise Machine', muscle: 'Shoulders', equipment: 'Machine', type: 'Isolation' },
  { name: 'Lying Rear Delt Raise', muscle: 'Shoulders', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Pike Press (Incline)', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },
  { name: 'Strict Handstand Push-Up', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },

  // ── Biceps ──
  { name: 'Barbell Curl', muscle: 'Biceps', equipment: 'Barbell' },
  { name: 'EZ Bar Curl', muscle: 'Biceps', equipment: 'Barbell' },
  { name: 'Dumbbell Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Hammer Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Cross-Body Hammer Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Concentration Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Preacher Curl', muscle: 'Biceps', equipment: 'Barbell' },
  { name: 'Spider Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Reverse Curl', muscle: 'Biceps', equipment: 'Barbell' },
  { name: 'Cable Curl', muscle: 'Biceps', equipment: 'Cable' },
  { name: 'Cable Hammer Curl', muscle: 'Biceps', equipment: 'Cable' },
  { name: 'Drag Curl', muscle: 'Biceps', equipment: 'Barbell' },
  { name: 'Zottman Curl', muscle: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Bayesian Curl', muscle: 'Biceps', equipment: 'Cable' },
  { name: '21s', muscle: 'Biceps', equipment: 'Barbell' },
  { name: 'Chin-Up (biceps bias)', muscle: 'Biceps', equipment: 'Bodyweight', type: 'Compound', secondary: 'Back' },
  { name: 'Cable Rope Curl', muscle: 'Biceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Dumbbell EZ Curl', muscle: 'Biceps', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Incline Hammer Curl', muscle: 'Biceps', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Forearms' },
  { name: 'Reverse-Grip EZ Curl', muscle: 'Biceps', equipment: 'Barbell', type: 'Isolation', secondary: 'Forearms' },
  { name: 'Cable Preacher Curl', muscle: 'Biceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Machine Preacher Curl', muscle: 'Biceps', equipment: 'Machine', type: 'Isolation' },
  { name: 'Band Curl', muscle: 'Biceps', equipment: 'Band', type: 'Isolation' },
  { name: 'Incline EZ-Bar Curl', muscle: 'Biceps', equipment: 'Barbell', type: 'Isolation' },
  { name: 'One-Arm Cable Curl', muscle: 'Biceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Zottman Curl (twist)', muscle: 'Biceps', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Forearms' },
  { name: 'Spider Hammer Curl', muscle: 'Biceps', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Forearms' },
  { name: '45° Incline Curl', muscle: 'Biceps', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Rope Curl (cable)', muscle: 'Biceps', equipment: 'Cable', type: 'Isolation' },

  // ── Triceps ──
  { name: 'Tricep Pushdown', muscle: 'Triceps', equipment: 'Cable' },
  { name: 'V-Bar Pushdown', muscle: 'Triceps', equipment: 'Cable' },
  { name: 'Rope Pushdown', muscle: 'Triceps', equipment: 'Cable' },
  { name: 'Overhead Tricep Extension', muscle: 'Triceps', equipment: 'Cable' },
  { name: 'Dumbbell Overhead Extension', muscle: 'Triceps', equipment: 'Dumbbell' },
  { name: 'Skull Crusher', muscle: 'Triceps', equipment: 'Barbell' },
  { name: 'EZ Bar Skull Crusher', muscle: 'Triceps', equipment: 'Barbell' },
  { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', equipment: 'Dumbbell' },
  { name: 'Incline Skull Crusher', muscle: 'Triceps', equipment: 'Dumbbell' },
  { name: 'Close Grip Bench Press', muscle: 'Triceps', equipment: 'Barbell' },
  { name: 'JM Press', muscle: 'Triceps', equipment: 'Barbell' },
  { name: 'Dips', muscle: 'Triceps', equipment: 'Bodyweight' },
  { name: 'Bench Dips', muscle: 'Triceps', equipment: 'Bodyweight' },
  { name: 'Diamond Push-Up', muscle: 'Triceps', equipment: 'Bodyweight' },
  { name: 'Tricep Kickback', muscle: 'Triceps', equipment: 'Dumbbell' },
  { name: 'Tate Press', muscle: 'Triceps', equipment: 'Dumbbell' },
  { name: 'French Press', muscle: 'Triceps', equipment: 'Barbell' },
  { name: 'Single Arm Cable Extension', muscle: 'Triceps', equipment: 'Cable' },
  { name: 'Cable Pushdown (bar)', muscle: 'Triceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Rope Overhead Extension', muscle: 'Triceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Dumbbell Floor Press (close)', muscle: 'Triceps', equipment: 'Dumbbell', type: 'Compound' },
  { name: 'Close-Grip Floor Press', muscle: 'Triceps', equipment: 'Barbell', type: 'Compound' },
  { name: 'EZ Bar Overhead Extension', muscle: 'Triceps', equipment: 'Barbell', type: 'Isolation' },
  { name: 'Cable Pullover (triceps)', muscle: 'Triceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Reverse-Grip Tricep Pushdown', muscle: 'Triceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Band Pushdown', muscle: 'Triceps', equipment: 'Band', type: 'Isolation' },
  { name: 'Bodyweight Skull Crusher', muscle: 'Triceps', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Diamond Push-Up (decline)', muscle: 'Triceps', equipment: 'Bodyweight', type: 'Compound' },
  { name: 'Ring Dips', muscle: 'Triceps', equipment: 'Bodyweight', type: 'Compound', secondary: 'Chest' },
  { name: 'Weighted Dips', muscle: 'Triceps', equipment: 'Bodyweight', type: 'Compound', secondary: 'Chest' },
  { name: 'JM Press (EZ)', muscle: 'Triceps', equipment: 'Barbell', type: 'Compound' },
  { name: 'Machine Dips', muscle: 'Triceps', equipment: 'Machine', type: 'Compound', secondary: 'Chest' },
  { name: 'Cable Cross-Body Extension', muscle: 'Triceps', equipment: 'Cable', type: 'Isolation' },
  { name: 'Lying Dumbbell Extension', muscle: 'Triceps', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Seated Dumbbell Extension', muscle: 'Triceps', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Close-Grip Push-Up', muscle: 'Triceps', equipment: 'Bodyweight', type: 'Compound' },

  // ── Forearms ──
  { name: 'Wrist Curl', muscle: 'Forearms', equipment: 'Barbell' },
  { name: 'Reverse Wrist Curl', muscle: 'Forearms', equipment: 'Barbell' },
  { name: 'Farmer\'s Walk', muscle: 'Forearms', equipment: 'Dumbbell' },
  { name: 'Dead Hang', muscle: 'Forearms', equipment: 'Bodyweight' },
  { name: 'Plate Pinch', muscle: 'Forearms', equipment: 'Plate' },
  { name: 'Wrist Roller', muscle: 'Forearms', equipment: 'Cable' },
  { name: 'Towel Pull-Up', muscle: 'Forearms', equipment: 'Bodyweight' },
  { name: 'Finger Curl', muscle: 'Forearms', equipment: 'Barbell' },
  { name: 'Dumbbell Wrist Curl', muscle: 'Forearms', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Reverse EZ Curl', muscle: 'Forearms', equipment: 'Barbell', type: 'Isolation', secondary: 'Biceps' },
  { name: 'Sledgehammer Strike', muscle: 'Forearms', equipment: 'Plate', type: 'Isolation', secondary: 'Core' },
  { name: 'Grip Crusher', muscle: 'Forearms', equipment: 'Other', type: 'Isolation' },
  { name: 'Towel Hang', muscle: 'Forearms', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Supported Wrist Roller', muscle: 'Forearms', equipment: 'Barbell', type: 'Isolation' },
  { name: 'Farmer Carry (heavy)', muscle: 'Forearms', equipment: 'Dumbbell', type: 'Compound', secondary: 'Traps' },
  { name: 'Kettlebell Hold (bottoms-up)', muscle: 'Forearms', equipment: 'Kettlebell', type: 'Isolation', secondary: 'Shoulders' },
  { name: 'Rope Climb', muscle: 'Forearms', equipment: 'Bodyweight', type: 'Compound', secondary: 'Back' },

  // ── Traps ──
  { name: 'Barbell Shrug', muscle: 'Traps', equipment: 'Barbell' },
  { name: 'Dumbbell Shrug', muscle: 'Traps', equipment: 'Dumbbell' },
  { name: 'Cable Shrug', muscle: 'Traps', equipment: 'Cable' },
  { name: 'Snatch Grip Shrug', muscle: 'Traps', equipment: 'Barbell' },
  { name: 'Rack Pull', muscle: 'Traps', equipment: 'Barbell' },
  { name: 'Upright Row', muscle: 'Traps', equipment: 'Barbell' },
  { name: 'Kettlebell Shrug', muscle: 'Traps', equipment: 'Kettlebell', type: 'Isolation' },
  { name: 'Trap Bar Shrug', muscle: 'Traps', equipment: 'Barbell', type: 'Isolation' },
  { name: 'Farmers Carry Step-Up', muscle: 'Traps', equipment: 'Dumbbell', type: 'Compound', secondary: 'Core' },
  { name: 'Dumbbell High Pull', muscle: 'Traps', equipment: 'Dumbbell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Neck Harness', muscle: 'Traps', equipment: 'Other', type: 'Isolation' },
  { name: 'Plate Shrug', muscle: 'Traps', equipment: 'Plate', type: 'Isolation' },
  { name: 'Underhand Shrug', muscle: 'Traps', equipment: 'Barbell', type: 'Isolation' },
  { name: 'Clean High Pull', muscle: 'Traps', equipment: 'Barbell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Trap Bar Deadlift (high)', muscle: 'Traps', equipment: 'Barbell', type: 'Compound', secondary: 'Full Body' },

  // ── Quads ──
  { name: 'Squat', muscle: 'Quads', equipment: 'Barbell' },
  { name: 'Front Squat', muscle: 'Quads', equipment: 'Barbell' },
  { name: 'Box Squat', muscle: 'Quads', equipment: 'Barbell' },
  { name: 'Pause Squat', muscle: 'Quads', equipment: 'Barbell' },
  { name: 'Hack Squat', muscle: 'Quads', equipment: 'Machine' },
  { name: 'Goblet Squat', muscle: 'Quads', equipment: 'Dumbbell' },
  { name: 'Bulgarian Split Squat', muscle: 'Quads', equipment: 'Dumbbell' },
  { name: 'Leg Press', muscle: 'Quads', equipment: 'Machine' },
  { name: 'Leg Extension', muscle: 'Quads', equipment: 'Machine' },
  { name: 'Sissy Squat', muscle: 'Quads', equipment: 'Bodyweight' },
  { name: 'Pistol Squat', muscle: 'Quads', equipment: 'Bodyweight' },
  { name: 'Lunge', muscle: 'Quads', equipment: 'Dumbbell' },
  { name: 'Reverse Lunge', muscle: 'Quads', equipment: 'Dumbbell' },
  { name: 'Walking Lunge', muscle: 'Quads', equipment: 'Dumbbell' },
  { name: 'Step-Up', muscle: 'Quads', equipment: 'Dumbbell' },
  { name: 'Wall Sit', muscle: 'Quads', equipment: 'Bodyweight' },
  { name: 'Box Jump', muscle: 'Quads', equipment: 'Bodyweight' },
  { name: 'Cossack Squat', muscle: 'Quads', equipment: 'Bodyweight' },
  { name: 'Kettlebell Goblet Squat', muscle: 'Quads', equipment: 'Kettlebell' },
  { name: 'Low-Bar Back Squat', muscle: 'Quads', equipment: 'Barbell', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'High-Bar Back Squat', muscle: 'Quads', equipment: 'Barbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Tempo Squat', muscle: 'Quads', equipment: 'Barbell', type: 'Compound' },
  { name: 'Pin Squat', muscle: 'Quads', equipment: 'Barbell', type: 'Compound' },
  { name: 'Belt Squat', muscle: 'Quads', equipment: 'Machine', type: 'Compound' },
  { name: 'Smith Machine Squat', muscle: 'Quads', equipment: 'Machine', type: 'Compound' },
  { name: 'Leg Press (single leg)', muscle: 'Quads', equipment: 'Machine', type: 'Compound' },
  { name: 'Hack Squat (sled)', muscle: 'Quads', equipment: 'Machine', type: 'Compound' },
  { name: 'Dumbbell Split Squat (rear)', muscle: 'Quads', equipment: 'Dumbbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Lateral Step-Up', muscle: 'Quads', equipment: 'Dumbbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Barbell Lunge', muscle: 'Quads', equipment: 'Barbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Curtsy Lunge', muscle: 'Quads', equipment: 'Dumbbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Leg Extension (single)', muscle: 'Quads', equipment: 'Machine', type: 'Isolation' },
  { name: 'Reverse Lunge (elevated)', muscle: 'Quads', equipment: 'Bodyweight', type: 'Compound', secondary: 'Glutes' },
  { name: 'Sled Leg Press (feet high)', muscle: 'Quads', equipment: 'Machine', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Chained Squat', muscle: 'Quads', equipment: 'Barbell', type: 'Compound' },
  { name: 'Frankenstein Squat', muscle: 'Quads', equipment: 'Barbell', type: 'Compound', secondary: 'Core' },
  { name: 'Split Squat (Bulgarian, front foot)', muscle: 'Quads', equipment: 'Dumbbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Box Jump (single leg)', muscle: 'Quads', equipment: 'Bodyweight', type: 'Compound', secondary: 'Calves' },

  // ── Hamstrings ──
  { name: 'Romanian Deadlift', muscle: 'Hamstrings', equipment: 'Barbell' },
  { name: 'Stiff Leg Deadlift', muscle: 'Hamstrings', equipment: 'Barbell' },
  { name: 'Single Leg RDL', muscle: 'Hamstrings', equipment: 'Dumbbell' },
  { name: 'Leg Curl', muscle: 'Hamstrings', equipment: 'Machine' },
  { name: 'Nordic Curl', muscle: 'Hamstrings', equipment: 'Bodyweight' },
  { name: 'Glute Ham Raise', muscle: 'Hamstrings', equipment: 'Machine' },
  { name: 'Good Morning', muscle: 'Hamstrings', equipment: 'Barbell' },
  { name: 'Kettlebell Swing', muscle: 'Hamstrings', equipment: 'Kettlebell' },
  { name: 'Swiss Ball Leg Curl', muscle: 'Hamstrings', equipment: 'Bodyweight' },
  { name: 'Sliding Leg Curl', muscle: 'Hamstrings', equipment: 'Bodyweight' },
  { name: 'Straight Leg Deadlift', muscle: 'Hamstrings', equipment: 'Dumbbell' },
  { name: 'Seated Leg Curl', muscle: 'Hamstrings', equipment: 'Machine', type: 'Isolation' },
  { name: 'Lying Leg Curl', muscle: 'Hamstrings', equipment: 'Machine', type: 'Isolation' },
  { name: 'Single-Leg Leg Curl', muscle: 'Hamstrings', equipment: 'Machine', type: 'Isolation' },
  { name: 'Nordic Curl (assisted)', muscle: 'Hamstrings', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Band Leg Curl', muscle: 'Hamstrings', equipment: 'Band', type: 'Isolation' },
  { name: 'Dumbbell Straight Leg Deadlift', muscle: 'Hamstrings', equipment: 'Dumbbell', type: 'Compound', secondary: 'Back' },
  { name: 'Sumo RDL', muscle: 'Hamstrings', equipment: 'Barbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Kettlebell RDL', muscle: 'Hamstrings', equipment: 'Kettlebell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Single-Leg RDL (band)', muscle: 'Hamstrings', equipment: 'Band', type: 'Compound', secondary: 'Core' },
  { name: 'Glute Ham Developer (GHD)', muscle: 'Hamstrings', equipment: 'Machine', type: 'Compound', secondary: 'Glutes' },
  { name: 'Ball Leg Curl (double)', muscle: 'Hamstrings', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Sled Hamstring Curl', muscle: 'Hamstrings', equipment: 'Sled', type: 'Isolation' },
  { name: 'Razor Curl', muscle: 'Hamstrings', equipment: 'Cable', type: 'Isolation' },

  // ── Glutes ──
  { name: 'Hip Thrust', muscle: 'Glutes', equipment: 'Barbell' },
  { name: 'Single Leg Hip Thrust', muscle: 'Glutes', equipment: 'Dumbbell' },
  { name: 'Glute Bridge', muscle: 'Glutes', equipment: 'Bodyweight' },
  { name: 'Single Leg Glute Bridge', muscle: 'Glutes', equipment: 'Bodyweight' },
  { name: 'Cable Pull-Through', muscle: 'Glutes', equipment: 'Cable' },
  { name: 'Donkey Kick', muscle: 'Glutes', equipment: 'Bodyweight' },
  { name: 'Fire Hydrant', muscle: 'Glutes', equipment: 'Bodyweight' },
  { name: 'Clamshell', muscle: 'Glutes', equipment: 'Bodyweight' },
  { name: 'Kickback (Cable)', muscle: 'Glutes', equipment: 'Cable' },
  { name: 'Reverse Hyperextension', muscle: 'Glutes', equipment: 'Bodyweight' },
  { name: 'Step-Up', muscle: 'Glutes', equipment: 'Dumbbell' },
  { name: 'Barbell Glute Bridge', muscle: 'Glutes', equipment: 'Barbell', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Sumo Hip Thrust', muscle: 'Glutes', equipment: 'Barbell', type: 'Compound', secondary: 'Adductors' },
  { name: 'Elevated Hip Thrust', muscle: 'Glutes', equipment: 'Barbell', type: 'Compound' },
  { name: 'Bulgarian Split Squat (glute focus)', muscle: 'Glutes', equipment: 'Bodyweight', type: 'Compound', secondary: 'Quads' },
  { name: 'Cable Hip Abduction', muscle: 'Glutes', equipment: 'Cable', type: 'Isolation', secondary: 'Abductors' },
  { name: 'Band Hip Thrust', muscle: 'Glutes', equipment: 'Band', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Weighted Glute Bridge', muscle: 'Glutes', equipment: 'Plate', type: 'Compound', secondary: 'Hamstrings' },
  { name: 'Kickback (cable, single)', muscle: 'Glutes', equipment: 'Cable', type: 'Isolation' },
  { name: 'Standing Glute Kickback (band)', muscle: 'Glutes', equipment: 'Band', type: 'Isolation' },
  { name: 'Hip Thrust (single leg)', muscle: 'Glutes', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Hamstrings' },
  { name: 'Curtsy Step-Up', muscle: 'Glutes', equipment: 'Dumbbell', type: 'Compound', secondary: 'Adductors' },
  { name: 'Band Lateral Walk', muscle: 'Glutes', equipment: 'Band', type: 'Isolation', secondary: 'Abductors' },
  { name: 'Kettlebell Swing (single arm)', muscle: 'Glutes', equipment: 'Kettlebell', type: 'Compound', secondary: 'Hamstrings' },

  // ── Calves ──
  { name: 'Standing Calf Raise', muscle: 'Calves', equipment: 'Barbell' },
  { name: 'Seated Calf Raise', muscle: 'Calves', equipment: 'Machine' },
  { name: 'Calf Press on Leg Press', muscle: 'Calves', equipment: 'Machine' },
  { name: 'Donkey Calf Raise', muscle: 'Calves', equipment: 'Bodyweight' },
  { name: 'Single Leg Calf Raise', muscle: 'Calves', equipment: 'Dumbbell' },
  { name: 'Box Jump', muscle: 'Calves', equipment: 'Bodyweight' },
  { name: 'Pogo Jump', muscle: 'Calves', equipment: 'Bodyweight' },
  { name: 'Skipping', muscle: 'Calves', equipment: 'Bodyweight' },
  { name: 'Seated Calf Raise (single)', muscle: 'Calves', equipment: 'Machine', type: 'Isolation' },
  { name: 'Leg Press Calf Raise', muscle: 'Calves', equipment: 'Machine', type: 'Isolation' },
  { name: 'Smith Machine Calf Raise', muscle: 'Calves', equipment: 'Machine', type: 'Isolation' },
  { name: 'Calf Raise (toes elevated)', muscle: 'Calves', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Farmer Carry on Toes', muscle: 'Calves', equipment: 'Dumbbell', type: 'Isolation' },
  { name: 'Sprint Work (calves)', muscle: 'Calves', equipment: 'Bodyweight', type: 'Compound', secondary: 'Glutes' },
  { name: 'Mountain Climbing (fast)', muscle: 'Calves', equipment: 'Bodyweight', type: 'Compound', secondary: 'Core' },
  { name: 'High Knees', muscle: 'Calves', equipment: 'Bodyweight', type: 'Compound', secondary: 'Quads' },
  { name: 'Bungee Calf Raise', muscle: 'Calves', equipment: 'Band', type: 'Isolation' },
  { name: 'Incline Treadmill Walk (high)', muscle: 'Calves', equipment: 'Machine', type: 'Compound', secondary: 'Glutes' },

  // ── Adductors / Abductors ──
  { name: 'Seated Hip Adduction', muscle: 'Adductors', equipment: 'Machine' },
  { name: 'Seated Hip Abduction', muscle: 'Abductors', equipment: 'Machine' },
  { name: 'Lateral Lunge', muscle: 'Adductors', equipment: 'Bodyweight' },
  { name: 'Copenhagen Plank', muscle: 'Adductors', equipment: 'Bodyweight' },
  { name: 'Sumo Squat', muscle: 'Adductors', equipment: 'Dumbbell' },
  { name: 'Side Lying Leg Raise', muscle: 'Abductors', equipment: 'Bodyweight' },
  { name: 'Hip Adduction Machine', muscle: 'Adductors', equipment: 'Machine', type: 'Isolation' },
  { name: 'Hip Abduction Machine', muscle: 'Abductors', equipment: 'Machine', type: 'Isolation' },
  { name: 'Cable Hip Adduction', muscle: 'Adductors', equipment: 'Cable', type: 'Isolation' },
  { name: 'Side Lunge (band)', muscle: 'Adductors', equipment: 'Band', type: 'Compound', secondary: 'Glutes' },
  { name: 'Copenhagen Side Plank', muscle: 'Adductors', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Core' },
  { name: 'Suitcase Squat', muscle: 'Adductors', equipment: 'Dumbbell', type: 'Compound', secondary: 'Quads' },
  { name: 'Frog Pump', muscle: 'Adductors', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Glutes' },
  { name: 'Seated Band Abduction', muscle: 'Abductors', equipment: 'Band', type: 'Isolation' },

  // ── Core ──
  { name: 'Plank', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Side Plank', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Crunch', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Bicycle Crunch', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Russian Twist', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Weighted Russian Twist', muscle: 'Core', equipment: 'Plate' },
  { name: 'Ab Rollout', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Barbell Rollout', muscle: 'Core', equipment: 'Barbell' },
  { name: 'Hanging Leg Raise', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Cable Crunch', muscle: 'Core', equipment: 'Cable' },
  { name: 'Dead Bug', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Pallof Press', muscle: 'Core', equipment: 'Cable' },
  { name: 'Windmill', muscle: 'Core', equipment: 'Kettlebell' },
  { name: 'Mountain Climber', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Dragon Flag', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'L-Sit', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'V-Up', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Toes to Bar', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Reverse Crunch', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Leg Lowers', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Hollow Body Hold', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Bird Dog', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Sit-Up', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Jackknife', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Medicine Ball Slam', muscle: 'Core', equipment: 'Medicine Ball' },
  { name: 'Landmine Twist', muscle: 'Core', equipment: 'Barbell' },
  { name: 'Oblique Crunch', muscle: 'Core', equipment: 'Bodyweight' },
  { name: 'Cable Woodchopper', muscle: 'Core', equipment: 'Cable', type: 'Compound', secondary: 'Obliques' },
  { name: 'Anti-Rotation Press', muscle: 'Core', equipment: 'Cable', type: 'Isolation' },
  { name: 'Hanging Knee Raise', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Barbell Ab Wheel', muscle: 'Core', equipment: 'Barbell', type: 'Compound', secondary: 'Lats' },
  { name: 'Dumbbell Side Bend', muscle: 'Core', equipment: 'Dumbbell', type: 'Isolation', secondary: 'Obliques' },
  { name: 'Plank (weighted)', muscle: 'Core', equipment: 'Plate', type: 'Isolation' },
  { name: 'Bicycle Crunch (slow)', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Obliques' },
  { name: 'Cable Kneeling Crunch', muscle: 'Core', equipment: 'Cable', type: 'Isolation' },
  { name: 'Reverse Plank', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Glutes' },
  { name: 'Flutter Kick', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Quads' },
  { name: 'Sit-Up (weighted)', muscle: 'Core', equipment: 'Plate', type: 'Isolation' },
  { name: 'Medicine Ball Russian Twist', muscle: 'Core', equipment: 'Medicine Ball', type: 'Isolation', secondary: 'Obliques' },
  { name: 'Copenhagen Hold', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Adductors' },
  { name: 'Side Plank Hip Dip', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Obliques' },
  { name: 'Pallof Press (band)', muscle: 'Core', equipment: 'Band', type: 'Isolation' },
  { name: 'Ab Crunch Machine', muscle: 'Core', equipment: 'Machine', type: 'Isolation' },
  { name: 'Towel Ab Row', muscle: 'Core', equipment: 'Bodyweight', type: 'Compound', secondary: 'Back' },
  { name: 'Standing Cable Crunch', muscle: 'Core', equipment: 'Cable', type: 'Isolation' },
  { name: 'Hanging L-Sit Hold', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Quads' },
  { name: 'Landmine Anti-Rotation', muscle: 'Core', equipment: 'Barbell', type: 'Isolation' },

  // ── Full Body ──
  { name: 'Power Clean', muscle: 'Full Body', equipment: 'Barbell' },
  { name: 'Clean and Jerk', muscle: 'Full Body', equipment: 'Barbell' },
  { name: 'Snatch', muscle: 'Full Body', equipment: 'Barbell' },
  { name: 'Clean Pull', muscle: 'Full Body', equipment: 'Barbell' },
  { name: 'Snatch Pull', muscle: 'Full Body', equipment: 'Barbell' },
  { name: 'Thruster', muscle: 'Full Body', equipment: 'Barbell' },
  { name: 'Burpee', muscle: 'Full Body', equipment: 'Bodyweight' },
  { name: 'Turkish Get-Up', muscle: 'Full Body', equipment: 'Kettlebell' },
  { name: 'Kettlebell Clean', muscle: 'Full Body', equipment: 'Kettlebell' },
  { name: 'Kettlebell Snatch', muscle: 'Full Body', equipment: 'Kettlebell' },
  { name: 'Battle Ropes', muscle: 'Full Body', equipment: 'Cable' },
  { name: 'Sled Push', muscle: 'Full Body', equipment: 'Sled' },
  { name: 'Sled Pull', muscle: 'Full Body', equipment: 'Sled' },
  { name: 'Farmer\'s Walk', muscle: 'Full Body', equipment: 'Dumbbell' },
  { name: 'Suitcase Carry', muscle: 'Full Body', equipment: 'Dumbbell' },
  { name: 'Waiter Carry', muscle: 'Full Body', equipment: 'Dumbbell' },
  { name: 'Bear Crawl', muscle: 'Full Body', equipment: 'Bodyweight' },
  { name: 'Crab Walk', muscle: 'Full Body', equipment: 'Bodyweight' },
  { name: 'Medicine Ball Slam', muscle: 'Full Body', equipment: 'Medicine Ball' },
  { name: 'Dumbbell Snatch', muscle: 'Full Body', equipment: 'Dumbbell' },
  { name: 'Devil\'s Press', muscle: 'Full Body', equipment: 'Dumbbell' },
  { name: 'Zercher Squat', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Quads' },
  { name: 'Zercher Deadlift', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Back' },
  { name: 'Overhead Squat', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Dumbbell Complex (clean & press)', muscle: 'Full Body', equipment: 'Dumbbell', type: 'Compound' },
  { name: 'Kettlebell Thruster', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Kettlebell Windmill', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound', secondary: 'Core' },
  { name: 'Sled Drag (reverse)', muscle: 'Full Body', equipment: 'Sled', type: 'Compound' },
  { name: 'Tire Flip', muscle: 'Full Body', equipment: 'Other', type: 'Compound', secondary: 'Back' },
  { name: 'Sandbag Clean', muscle: 'Full Body', equipment: 'Other', type: 'Compound' },
  { name: 'Sandbag Shoulder', muscle: 'Full Body', equipment: 'Other', type: 'Compound', secondary: 'Legs' },
  { name: 'Jump Rope Complex', muscle: 'Full Body', equipment: 'Other', type: 'Compound', secondary: 'Calves' },
  { name: 'Wall Ball', muscle: 'Full Body', equipment: 'Medicine Ball', type: 'Compound', secondary: 'Quads' },
  { name: 'Kettlebell Clean & Press', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound' },
  { name: 'Log Press', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Atlas Stone Lift', muscle: 'Full Body', equipment: 'Other', type: 'Compound', secondary: 'Back' },
  { name: 'Yoke Carry', muscle: 'Full Body', equipment: 'Other', type: 'Compound', secondary: 'Traps' },
  { name: 'Gorilla Row', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound', secondary: 'Back' },
  { name: 'Tactical Lunge', muscle: 'Full Body', equipment: 'Dumbbell', type: 'Compound', secondary: 'Glutes' },
  { name: 'Bent Press', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound', secondary: 'Core' },
  { name: 'Dumbbell Overhead Carry', muscle: 'Full Body', equipment: 'Dumbbell', type: 'Compound', secondary: 'Core' },
  { name: 'Broad Jump', muscle: 'Full Body', equipment: 'Bodyweight', type: 'Compound', secondary: 'Quads' },
  { name: 'Burpee Pull-Up', muscle: 'Full Body', equipment: 'Bodyweight', type: 'Compound', secondary: 'Back' },
  { name: 'Bear Crawl (weighted)', muscle: 'Full Body', equipment: 'Plate', type: 'Compound', secondary: 'Core' },
  { name: 'Kettlebell Figure 8', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound', secondary: 'Core' },
  { name: 'Muscle Snatch', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound' },
  { name: 'Hang Snatch', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Back' },
  { name: 'Push Jerk', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Split Jerk', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound', secondary: 'Shoulders' },
  { name: 'Snatch Balance', muscle: 'Full Body', equipment: 'Barbell', type: 'Compound' },
  { name: 'Kettlebell Swing Double', muscle: 'Full Body', equipment: 'Kettlebell', type: 'Compound', secondary: 'Glutes' },
  // ── Calisthenics skills ──
  { name: 'Front Lever Hold', muscle: 'Full Body', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Core' },
  { name: 'Back Lever Hold', muscle: 'Full Body', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Chest' },
  { name: 'Planche (tuck)', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Core' },
  { name: 'Planche (full)', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Chest' },
  { name: 'Human Flag', muscle: 'Core', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Obliques' },
  { name: 'Bar Muscle-Up', muscle: 'Back', equipment: 'Bodyweight', type: 'Compound', secondary: 'Biceps' },
  { name: 'Ring Muscle-Up', muscle: 'Back', equipment: 'Other', type: 'Compound', secondary: 'Triceps' },
  { name: 'Handstand Walk', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Compound', secondary: 'Core' },
  { name: 'Wall Handstand Hold', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Core' },
  { name: 'Pistol Squat (assisted)', muscle: 'Quads', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Glutes' },
  { name: 'Shrimp Squat', muscle: 'Quads', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Glutes' },
  { name: 'Archer Push-Up', muscle: 'Chest', equipment: 'Bodyweight', type: 'Compound', secondary: 'Triceps' },
  { name: 'Pseudo Planche Push-Up', muscle: 'Shoulders', equipment: 'Bodyweight', type: 'Compound', secondary: 'Core' },
  { name: 'Nordic Curl Negative', muscle: 'Hamstrings', equipment: 'Bodyweight', type: 'Isolation' },
  // ── Mobility & Recovery ──
  { name: 'World\'s Greatest Stretch', muscle: 'Full Body', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Hip Flexors' },
  { name: '90/90 Hip Switch', muscle: 'Glutes', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Adductors' },
  { name: 'Couch Stretch', muscle: 'Quads', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Hip Flexors' },
  { name: 'Pigeon Pose', muscle: 'Glutes', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Jefferson Curl', muscle: 'Hamstrings', equipment: 'Barbell', type: 'Isolation', secondary: 'Spinal Erectors' },
  { name: 'Thoracic Extension over Roller', muscle: 'Back', equipment: 'Other', type: 'Isolation' },
  { name: 'Shoulder Dislocates (band)', muscle: 'Shoulders', equipment: 'Band', type: 'Isolation' },
  { name: 'Ankle Dorsiflexion Rock', muscle: 'Calves', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Wrist Prep / Front-Rack Stretch', muscle: 'Forearms', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Scapular Pull-Up Hang', muscle: 'Back', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Cat-Cow', muscle: 'Back', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Downward Dog to Cobra Flow', muscle: 'Full Body', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Deep Squat Hold', muscle: 'Quads', equipment: 'Bodyweight', type: 'Isolation', secondary: 'Adductors' },
  { name: 'Foam Roll — Quads', muscle: 'Quads', equipment: 'Other', type: 'Isolation' },
  { name: 'Foam Roll — Upper Back', muscle: 'Back', equipment: 'Other', type: 'Isolation' },
  { name: 'Band Pull-Apart (mobility)', muscle: 'Shoulders', equipment: 'Band', type: 'Isolation', secondary: 'Upper Back' },
];

// ── Neck (dedicated group for neck strengthening) ─────────────────────────
const NECK_EXERCISES: ExerciseEntry[] = [
  { name: 'Neck Harness Raise', muscle: 'Neck', equipment: 'Other', type: 'Isolation' },
  { name: 'Neck Flexion (plate)', muscle: 'Neck', equipment: 'Plate', type: 'Isolation' },
  { name: 'Neck Extension (plate)', muscle: 'Neck', equipment: 'Plate', type: 'Isolation' },
  { name: 'Lateral Neck Raise', muscle: 'Neck', equipment: 'Other', type: 'Isolation' },
  { name: 'Isometric Neck Hold', muscle: 'Neck', equipment: 'Bodyweight', type: 'Isolation' },
  { name: 'Neck Bridge (isometric)', muscle: 'Neck', equipment: 'Bodyweight', type: 'Isolation' },
];
EXERCISE_LIBRARY.push(...NECK_EXERCISES);

const MUSCLE_GROUP_ORDER: string[] = [
  'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms', 'Traps',
  'Quads', 'Hamstrings', 'Glutes', 'Calves', 'Adductors', 'Abductors',
  'Core', 'Full Body', 'Neck',
];

export function getMuscleGroups(): string[] {
  return MUSCLE_GROUP_ORDER;
}

export function searchExercises(query: string): ExerciseEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return EXERCISE_LIBRARY.filter(
    e => e.name.toLowerCase().includes(q) || e.muscle.toLowerCase().includes(q)
  ).slice(0, 8);
}

export function searchExercisesByMuscle(muscle: string): ExerciseEntry[] {
  if (!muscle.trim()) return [];
  const m = muscle.charAt(0).toUpperCase() + muscle.slice(1).toLowerCase();
  return EXERCISE_LIBRARY.filter(e => e.muscle === m);
}

export function searchExercisesByEquipment(equipment: string): ExerciseEntry[] {
  if (!equipment.trim()) return [];
  const q = equipment.toLowerCase();
  return EXERCISE_LIBRARY.filter(
    e => e.equipment?.toLowerCase() === q
  );
}
