export interface AssetEntry { ticker: string; name: string; type: 'Stock' | 'ETF' | 'Crypto' | 'Index' }

export const ASSET_LIBRARY: AssetEntry[] = [
  // US Stocks
  { ticker: 'AAPL',  name: 'Apple',            type: 'Stock' },
  { ticker: 'MSFT',  name: 'Microsoft',         type: 'Stock' },
  { ticker: 'GOOGL', name: 'Alphabet (Google)', type: 'Stock' },
  { ticker: 'AMZN',  name: 'Amazon',            type: 'Stock' },
  { ticker: 'META',  name: 'Meta',              type: 'Stock' },
  { ticker: 'TSLA',  name: 'Tesla',             type: 'Stock' },
  { ticker: 'NVDA',  name: 'Nvidia',            type: 'Stock' },
  { ticker: 'NFLX',  name: 'Netflix',           type: 'Stock' },
  { ticker: 'JPM',   name: 'JP Morgan',         type: 'Stock' },
  { ticker: 'V',     name: 'Visa',              type: 'Stock' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson', type: 'Stock' },
  { ticker: 'WMT',   name: 'Walmart',           type: 'Stock' },
  { ticker: 'DIS',   name: 'Disney',            type: 'Stock' },
  { ticker: 'PYPL',  name: 'PayPal',            type: 'Stock' },
  { ticker: 'UBER',  name: 'Uber',              type: 'Stock' },
  { ticker: 'SPOT',  name: 'Spotify',           type: 'Stock' },
  { ticker: 'AMD',   name: 'AMD',               type: 'Stock' },
  { ticker: 'CRM',   name: 'Salesforce',        type: 'Stock' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway', type: 'Stock' },
  { ticker: 'ORCL',  name: 'Oracle',            type: 'Stock' },
  { ticker: 'ADBE',  name: 'Adobe',             type: 'Stock' },
  { ticker: 'INTC',  name: 'Intel',             type: 'Stock' },
  { ticker: 'QCOM',  name: 'Qualcomm',          type: 'Stock' },
  { ticker: 'TSM',   name: 'Taiwan Semiconductor', type: 'Stock' },
  { ticker: 'ASML',  name: 'ASML',              type: 'Stock' },
  { ticker: 'SAP',   name: 'SAP',               type: 'Stock' },
  { ticker: 'KO',    name: 'Coca-Cola',         type: 'Stock' },
  { ticker: 'PEP',   name: 'PepsiCo',           type: 'Stock' },
  { ticker: 'MCD',   name: "McDonald's",        type: 'Stock' },
  { ticker: 'NKE',   name: 'Nike',              type: 'Stock' },
  { ticker: 'SBUX',  name: 'Starbucks',         type: 'Stock' },
  { ticker: 'PFE',   name: 'Pfizer',            type: 'Stock' },
  { ticker: 'XOM',   name: 'Exxon Mobil',       type: 'Stock' },
  { ticker: 'BA',    name: 'Boeing',            type: 'Stock' },
  { ticker: 'CAT',   name: 'Caterpillar',       type: 'Stock' },
  { ticker: 'PLTR',  name: 'Palantir',          type: 'Stock' },
  { ticker: 'SHOP',  name: 'Shopify',           type: 'Stock' },
  { ticker: 'SPOT',  name: 'Spotify',           type: 'Stock' },
  // European stocks
  { ticker: 'ENEL.MI', name: 'Enel',            type: 'Stock' },
  { ticker: 'ISP.MI',  name: 'Intesa Sanpaolo', type: 'Stock' },
  { ticker: 'UCG.MI',  name: 'UniCredit',       type: 'Stock' },
  { ticker: 'RACE.MI', name: 'Ferrari',         type: 'Stock' },
  { ticker: 'STLA.MI', name: 'Stellantis',      type: 'Stock' },
  { ticker: 'LDO.MI',  name: 'Leonardo',        type: 'Stock' },
  { ticker: 'ENI.MI',  name: 'Eni',             type: 'Stock' },
  { ticker: 'MC.PA',   name: 'LVMH',            type: 'Stock' },
  { ticker: 'ASML.AS', name: 'ASML (AMS)',      type: 'Stock' },
  { ticker: 'NOVO-B.CO', name: 'Novo Nordisk',  type: 'Stock' },
  // ETFs
  { ticker: 'SPY',   name: 'S&P 500 ETF',       type: 'ETF' },
  { ticker: 'QQQ',   name: 'Nasdaq-100 ETF',    type: 'ETF' },
  { ticker: 'VTI',   name: 'Total Market ETF',  type: 'ETF' },
  { ticker: 'VWRA',  name: 'Vanguard All World', type: 'ETF' },
  { ticker: 'IWDA',  name: 'iShares World ETF', type: 'ETF' },
  { ticker: 'CSPX',  name: 'iShares S&P 500',   type: 'ETF' },
  { ticker: 'VNQ',   name: 'Real Estate ETF',   type: 'ETF' },
  { ticker: 'GLD',   name: 'Gold ETF',          type: 'ETF' },
  { ticker: 'VOO',   name: 'Vanguard S&P 500',  type: 'ETF' },
  { ticker: 'QQQM',  name: 'Nasdaq-100 (Vanguard)', type: 'ETF' },
  { ticker: 'VEA',   name: 'Developed Markets ex-US', type: 'ETF' },
  { ticker: 'VWO',   name: 'Emerging Markets',  type: 'ETF' },
  { ticker: 'VXUS',  name: 'Total International', type: 'ETF' },
  { ticker: 'SCHD',  name: 'US Dividend Equity', type: 'ETF' },
  { ticker: 'EIMI',  name: 'iShares EM Small Cap', type: 'ETF' },
  { ticker: 'SLV',   name: 'Silver ETF',        type: 'ETF' },
  // Crypto
  { ticker: 'BTC',   name: 'Bitcoin',           type: 'Crypto' },
  { ticker: 'ETH',   name: 'Ethereum',          type: 'Crypto' },
  { ticker: 'SOL',   name: 'Solana',            type: 'Crypto' },
  { ticker: 'BNB',   name: 'Binance Coin',      type: 'Crypto' },
  { ticker: 'XRP',   name: 'Ripple',            type: 'Crypto' },
  { ticker: 'USDC',  name: 'USD Coin (stable)', type: 'Crypto' },
  { ticker: 'USDT',  name: 'Tether (stable)',   type: 'Crypto' },
  { ticker: 'ADA',   name: 'Cardano',           type: 'Crypto' },
  { ticker: 'DOT',   name: 'Polkadot',          type: 'Crypto' },
  { ticker: 'AVAX',  name: 'Avalanche',         type: 'Crypto' },
  { ticker: 'LINK',  name: 'Chainlink',         type: 'Crypto' },
  { ticker: 'MATIC', name: 'Polygon',           type: 'Crypto' },
  { ticker: 'DOGE',  name: 'Dogecoin',          type: 'Crypto' },
  { ticker: 'LTC',   name: 'Litecoin',          type: 'Crypto' },
  { ticker: 'WBTC',  name: 'Wrapped Bitcoin',   type: 'Crypto' },
  // Index / Bonds / Commodities
  { ticker: 'SPX',     name: 'S&P 500 Index',   type: 'Index' },
  { ticker: 'NDX',     name: 'Nasdaq-100 Index', type: 'Index' },
  { ticker: 'DJI',     name: 'Dow Jones Index', type: 'Index' },
  { ticker: 'FTSEMIB', name: 'FTSE MIB (Italy)', type: 'Index' },
  { ticker: 'DAX',     name: 'DAX (Germany)',   type: 'Index' },
  { ticker: 'UKX',     name: 'FTSE 100 (UK)',   type: 'Index' },
  { ticker: 'NKY',     name: 'Nikkei 225 (Japan)', type: 'Index' },
  { ticker: 'SX5E',    name: 'Euro Stoxx 50',   type: 'Index' },
  { ticker: 'BNDW',  name: 'Global Bond ETF',   type: 'Index' },
  { ticker: 'AGG',   name: 'US Bond Aggregate', type: 'Index' },
  { ticker: 'XAU',   name: 'Gold (spot)',       type: 'Index' },
];

export function searchAssets(query: string): AssetEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return ASSET_LIBRARY.filter(
    a => a.ticker.toLowerCase().includes(q) || a.name.toLowerCase().includes(q)
  ).slice(0, 8);
}
